version: "3"

services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: sdgjto345jkjfkdsfhdusrzfswer3
            SPARKY_DB_USER: ${SPARKY_DB_USER}
            SPARKY_DB_PW: ${SPARKY_DB_PW}
            BACKEND_DB_USER: ${BACKEND_DB_USER}
            BACKEND_DB_PW: ${BACKEND_DB_PW}
        volumes:
            - ./init-sparky.sh:/docker-entrypoint-initdb.d/1-init-sparky.sh
            - ./init-stu-mgmt-backend.sh:/docker-entrypoint-initdb.d/2-init-stu-mgmt-backend.sh

    sparky-service:
        image: stu-mgmt/sparky-service
        container_name: sparky-service
        ports:
            - 8080:8080
        depends_on:
            - postgres

    stu-mgmt-backend:
        image: stu-mgmt/stu-mgmt-backend
        container_name: stu-mgmt-backend
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - sparky-service

    stu-mgmt-frontend:
        image: stu-mgmt/stu-mgmt-frontend
        container_name: stu-mgmt-frontend
        ports:
            - 80:80
        depends_on:
            - stu-mgmt-backend
