server:
  port: 3000

db:
  type: "postgres"
  host: "postgres"
  port: 5432
  database: "studentmgmt_db"
  username: "studentmgmt_db_user"
  password: "__BACKEND_DB_PW__"
  synchronize: true

authentication:
  url: "http://sparky-service:8080"

logger:
  requests: false
  dbErrors: true
