server:
  port: 3000

db:
  type: "postgres"
  host: "postgres"
  port: 5432
  database: "studentmgmt_db"
  username: "studentmgmt_db_user"
  password: "__BACKEND_DB_PW__"
  synchronize: true

mailing:
  enabled: false
  smtp:
    host: "__BACKEND_MAIL_SERVER__"
    useSecureConnection: __BACKEND_MAIL_ENABLED__
    username: "__BACKEND_MAIL_USERNAME__"
    password: "__BACKEND_MAIL_PASSWORD__"
    port: __BACKEND_MAIL_PORT__

authentication:
  url: "http://sparky-service:8080"

logger:
  requests: false
  dbErrors: true
